[build-system]
requires = ["setuptools>=77"]
build-backend = "setuptools.build_meta"

[project]
name = "lemon"
version = "0.0.1"
description = "PyTorch-like numerical computation/tensor/autograd library"
readme = "README.md"
requires-python = ">=3.12"
license = "MIT"
authors = [
    {name = "remokasu"}
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]
dependencies = [
    "numpy>=2.5.0",
]

[project.optional-dependencies]
gpu = ["cupy>=9.0.0"]
plot = ["matplotlib>=3.0.0", "scikit-learn>=0.24.0"]
onnx = ["onnx>=1.10.0", "onnxruntime>=1.10.0"]
all = ["lemon[gpu,plot,onnx]"]

[dependency-groups]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=3.0.0",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/remokasu/lemon"
Repository = "https://github.com/remokasu/lemon"

[tool.setuptools.packages.find]
where = ["src"]
